const CURSOS_DATA = [
    {
        "id": 1,
        "slug": "excel-avanzado-",
        "category": "computacion",
        "modality": "presencial",
        "title": "Excel Avanzado ",
        "shortTitle": "Excel Avanzado ",
        "hours": "",
        "desc": "Excel Avanzado  - Curso técnico especializado.",
        "image": "../assets/temario_computacion.jpg",
        "pdf": "../assets/temarios/Computacion/Excel Avanzado .docx"
    },
    {
        "id": 2,
        "slug": "excel-basico",
        "category": "computacion",
        "modality": "presencial",
        "title": "Excel Basico",
        "shortTitle": "Excel Basico",
        "hours": "",
        "desc": "Excel Basico - Curso técnico especializado.",
        "image": "../assets/temario_computacion.jpg",
        "pdf": "../assets/temarios/Computacion/Excel Basico.docx"
    },
    {
        "id": 3,
        "slug": "excel-intermedio",
        "category": "computacion",
        "modality": "presencial",
        "title": "Excel Intermedio",
        "shortTitle": "Excel Intermedio",
        "hours": "",
        "desc": "Excel Intermedio - Curso técnico especializado.",
        "image": "../assets/temario_computacion.jpg",
        "pdf": "../assets/temarios/Computacion/Excel Intermedio.docx"
    },
    {
        "id": 4,
        "slug": "operacion-de-autoclaves-caldera-de-calefaccion-e-industrial",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Operacion de Autoclaves, caldera de calefaccion e industrial",
        "shortTitle": "Operacion de Autoclaves, caldera de calefaccion e industrial",
        "hours": "",
        "desc": "Operacion de Autoclaves, caldera de calefaccion e industrial - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/1.- Operacion de Autoclaves, caldera de calefaccion e industrial.docx"
    },
    {
        "id": 5,
        "slug": "operacion-de-autoclaves",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Operacion de Autoclaves",
        "shortTitle": "Operacion de Autoclaves",
        "hours": "",
        "desc": "Operacion de Autoclaves - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/2.- Operacion de Autoclaves.docx"
    },
    {
        "id": 6,
        "slug": "operacion-de-calderas-de-fluidos-termicos",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Operacion de Calderas de Fluidos Termicos",
        "shortTitle": "Operacion de Calderas de Fluidos Termicos",
        "hours": "",
        "desc": "Operacion de Calderas de Fluidos Termicos - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/3.- Operacion de Calderas de Fluidos Termicos.docx"
    },
    {
        "id": 7,
        "slug": "metrologia-ajustes-y-tolerancias",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Metrologia, Ajustes y Tolerancias",
        "shortTitle": "Metrologia, Ajustes y Tolerancias",
        "hours": "",
        "desc": "Metrologia, Ajustes y Tolerancias - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/4.- Metrologia, Ajustes y Tolerancias.docx"
    },
    {
        "id": 8,
        "slug": "soldadura-al-arco",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Soldadura al Arco",
        "shortTitle": "Soldadura al Arco",
        "hours": "",
        "desc": "Soldadura al Arco - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/5.- Soldadura al Arco.doc"
    },
    {
        "id": 9,
        "slug": "soldadura-tig---mig",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Soldadura TIG - MIG",
        "shortTitle": "Soldadura TIG - MIG",
        "hours": "",
        "desc": "Soldadura TIG - MIG - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/6.- Soldadura TIG - MIG.doc"
    },
    {
        "id": 10,
        "slug": "mecanica-mantencion-maquinas-y-equipos-industriales",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Mecanica, Mantencion Maquinas y Equipos Industriales",
        "shortTitle": "Mecanica, Mantencion Maquinas y Equipos Industriales",
        "hours": "",
        "desc": "Mecanica, Mantencion Maquinas y Equipos Industriales - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/7.- Mecanica, Mantencion Maquinas y Equipos Industriales.docx"
    },
    {
        "id": 11,
        "slug": "instalacion-electrica-domiciliaria",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Instalacion electrica domiciliaria",
        "shortTitle": "Instalacion electrica domiciliaria",
        "hours": "",
        "desc": "Instalacion electrica domiciliaria - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/8.- Instalacion electrica domiciliaria.docx"
    },
    {
        "id": 12,
        "slug": "administracion-de-bodegas",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Administracion de Bodegas",
        "shortTitle": "Administracion de Bodegas",
        "hours": "",
        "desc": "Administracion de Bodegas - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/9.- Administracion de Bodegas.docx"
    },
    {
        "id": 13,
        "slug": "hidrauica-industrial",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Hidrauica Industrial",
        "shortTitle": "Hidrauica Industrial",
        "hours": "",
        "desc": "Hidrauica Industrial - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/10.- Hidrauica Industrial.docx"
    },
    {
        "id": 14,
        "slug": "neumatica-basica",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Neumatica Basica",
        "shortTitle": "Neumatica Basica",
        "hours": "",
        "desc": "Neumatica Basica - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/11.- Neumatica Basica.docx"
    },
    {
        "id": 15,
        "slug": "operacion-y-mantencion-de-gruas-horquillas",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operacion y Mantencion de Gruas Horquillas",
        "shortTitle": "Operacion y Mantencion de Gruas Horquillas",
        "hours": "",
        "desc": "Operacion y Mantencion de Gruas Horquillas - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/1.- Operacion y Mantencion de Gruas Horquillas.docx"
    },
    {
        "id": 16,
        "slug": "operacion-y-mantencion-apiladores-electricos",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operacion y Mantencion Apiladores Electricos",
        "shortTitle": "Operacion y Mantencion Apiladores Electricos",
        "hours": "",
        "desc": "Operacion y Mantencion Apiladores Electricos - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/2.- Operacion y Mantencion Apiladores Electricos.docx"
    },
    {
        "id": 17,
        "slug": "operacion-de-alza-hombre-y-trabajos-en-altura",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operacion de Alza Hombre y Trabajos en Altura",
        "shortTitle": "Operacion de Alza Hombre y Trabajos en Altura",
        "hours": "",
        "desc": "Operacion de Alza Hombre y Trabajos en Altura - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/3.- Operacion de Alza Hombre y Trabajos en Altura.docx"
    },
    {
        "id": 18,
        "slug": "operacion-y-mantencion-de-puente-gruas-20-horas",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operacion y mantencion de puente gruas (20 horas)",
        "shortTitle": "Operacion y mantencion de puente gruas (20 horas)",
        "hours": "20",
        "desc": "Operacion y mantencion de puente gruas (20 horas) - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/4.- Operacion y mantencion de puente gruas (20 horas).docx"
    },
    {
        "id": 19,
        "slug": "operacion-y-mantencion-de-transpaleta-electrica",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operacion y Mantencion de Transpaleta Electrica",
        "shortTitle": "Operacion y Mantencion de Transpaleta Electrica",
        "hours": "",
        "desc": "Operacion y Mantencion de Transpaleta Electrica - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/5.- Operacion y Mantencion de Transpaleta Electrica.docx"
    },
    {
        "id": 20,
        "slug": "operacion-y-mantencion-de-cargador-frontal",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operacion y Mantencion de Cargador Frontal",
        "shortTitle": "Operacion y Mantencion de Cargador Frontal",
        "hours": "",
        "desc": "Operacion y Mantencion de Cargador Frontal - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/6.- Operacion y Mantencion de Cargador Frontal.docx"
    },
    {
        "id": 21,
        "slug": "operacion-y-mantencion-de-minicargador---cargador-frontal",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operacion y Mantencion de Minicargador - Cargador Frontal",
        "shortTitle": "Operacion y Mantencion de Minicargador - Cargador Frontal",
        "hours": "",
        "desc": "Operacion y Mantencion de Minicargador - Cargador Frontal - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/7.- Operacion y Mantencion de Minicargador - Cargador Frontal.docx"
    },
    {
        "id": 22,
        "slug": "operacion-de-camion-ampliroll",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operacion de camion Ampliroll",
        "shortTitle": "Operacion de camion Ampliroll",
        "hours": "",
        "desc": "Operacion de camion Ampliroll - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/8.- Operacion de camion Ampliroll.docx"
    },
    {
        "id": 23,
        "slug": "operacion-y-mantencion-de-retroexcavadora",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operacion y Mantencion de Retroexcavadora",
        "shortTitle": "Operacion y Mantencion de Retroexcavadora",
        "hours": "",
        "desc": "Operacion y Mantencion de Retroexcavadora - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/9.- Operacion y Mantencion de Retroexcavadora.docx"
    },
    {
        "id": 24,
        "slug": "rigger",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Rigger",
        "shortTitle": "Rigger",
        "hours": "",
        "desc": "Rigger - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/10.- Rigger.docx"
    },
    {
        "id": 25,
        "slug": "seguridad-en-trabajo-de-altura",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Seguridad en Trabajo de Altura",
        "shortTitle": "Seguridad en Trabajo de Altura",
        "hours": "",
        "desc": "Seguridad en Trabajo de Altura - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/1.- Seguridad en Trabajo de Altura.docx"
    },
    {
        "id": 26,
        "slug": "tecnicas-de-primeros-auxilios",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Tecnicas de Primeros Auxilios",
        "shortTitle": "Tecnicas de Primeros Auxilios",
        "hours": "",
        "desc": "Tecnicas de Primeros Auxilios - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/2.- Tecnicas de Primeros Auxilios.docx"
    },
    {
        "id": 27,
        "slug": "uso-y-manejo-de-extintores",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Uso y Manejo de Extintores",
        "shortTitle": "Uso y Manejo de Extintores",
        "hours": "",
        "desc": "Uso y Manejo de Extintores - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/3.- Uso y Manejo de Extintores.docx"
    },
    {
        "id": 28,
        "slug": "bpm",
        "category": "seguridad",
        "modality": "presencial",
        "title": "BPM",
        "shortTitle": "BPM",
        "hours": "",
        "desc": "BPM - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/4.- BPM.docx"
    },
    {
        "id": 29,
        "slug": "food-defense",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Food Defense",
        "shortTitle": "Food Defense",
        "hours": "",
        "desc": "Food Defense - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/5.- Food Defense.docx"
    },
    {
        "id": 30,
        "slug": "trabajo-en-espacios-confinados",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Trabajo en espacios confinados",
        "shortTitle": "Trabajo en espacios confinados",
        "hours": "",
        "desc": "Trabajo en espacios confinados - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/6.- Trabajo en espacios confinados.docx"
    },
    {
        "id": 31,
        "slug": "entrenamiento-de-brigadas-de-emergencia",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Entrenamiento de Brigadas de Emergencia",
        "shortTitle": "Entrenamiento de Brigadas de Emergencia",
        "hours": "",
        "desc": "Entrenamiento de Brigadas de Emergencia - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/7.- Entrenamiento de Brigadas de Emergencia.docx"
    },
    {
        "id": 32,
        "slug": "manejo-de-residuos-peligrosos",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Manejo de residuos peligrosos",
        "shortTitle": "Manejo de residuos peligrosos",
        "hours": "",
        "desc": "Manejo de residuos peligrosos - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/8.- Manejo de residuos peligrosos.docx"
    },
    {
        "id": 33,
        "slug": "prevencion-de-riesgos-electricos",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Prevencion de Riesgos Electricos",
        "shortTitle": "Prevencion de Riesgos Electricos",
        "hours": "",
        "desc": "Prevencion de Riesgos Electricos - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/9.- Prevencion de Riesgos Electricos.docx"
    },
    {
        "id": 34,
        "slug": "operacion-de-extintores-portatiles",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Operacion de Extintores Portatiles",
        "shortTitle": "Operacion de Extintores Portatiles",
        "hours": "",
        "desc": "Operacion de Extintores Portatiles - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/10.- Operacion de Extintores Portatiles.docx"
    },
    {
        "id": 35,
        "slug": "prevencion-de-riesgos-laborales-autocuidado-y-seguridad",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Prevencion de riesgos laborales, autocuidado y seguridad",
        "shortTitle": "Prevencion de riesgos laborales, autocuidado y seguridad",
        "hours": "",
        "desc": "Prevencion de riesgos laborales, autocuidado y seguridad - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/11.- Prevencion de riesgos laborales, autocuidado y seguridad.docx"
    }
];