// Auto-generated from /temarios/ - DO NOT EDIT MANUALLY
// Source of truth: assets/temarios/

const CURSOS_DATA = [
    {
        'id': 1,
        'slug': 'excel-avanzado',
        'category': 'computacion',
        'title': 'Excel Avanzado',
        'shortTitle': 'Excel Avanzado',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Computación.',
        'pdf': '../assets/temarios/Computacion/Excel Avanzado .docx',
        'image': '../assets/temario_computacion.jpg'
    },
    {
        'id': 2,
        'slug': 'excel-basico',
        'category': 'computacion',
        'title': 'Excel Basico',
        'shortTitle': 'Excel Basico',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Computación.',
        'pdf': '../assets/temarios/Computacion/Excel Basico.docx',
        'image': '../assets/temario_computacion.jpg'
    },
    {
        'id': 3,
        'slug': 'excel-intermedio',
        'category': 'computacion',
        'title': 'Excel Intermedio',
        'shortTitle': 'Excel Intermedio',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Computación.',
        'pdf': '../assets/temarios/Computacion/Excel Intermedio.docx',
        'image': '../assets/temario_computacion.jpg'
    },
    {
        'id': 4,
        'slug': 'operacion-de-autoclaves-caldera-de-calefaccion-e-industrial',
        'category': 'mantencion',
        'title': 'Operacion de Autoclaves, caldera de calefaccion e industrial',
        'shortTitle': 'Operacion de Autoclaves, caldera de calefaccion e industrial',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Mantención y Producción.',
        'pdf': '../assets/temarios/Mantencion y Produccion/1.- Operacion de Autoclaves, caldera de calefaccion e industrial.docx',
        'image': '../assets/temario_mantencionYproduccion.jpg'
    },
    {
        'id': 5,
        'slug': 'operacion-de-autoclaves',
        'category': 'mantencion',
        'title': 'Operacion de Autoclaves',
        'shortTitle': 'Operacion de Autoclaves',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Mantención y Producción.',
        'pdf': '../assets/temarios/Mantencion y Produccion/2.- Operacion de Autoclaves.docx',
        'image': '../assets/temario_mantencionYproduccion.jpg'
    },
    {
        'id': 6,
        'slug': 'operacion-de-calderas-de-fluidos-termicos',
        'category': 'mantencion',
        'title': 'Operacion de Calderas de Fluidos Termicos',
        'shortTitle': 'Operacion de Calderas de Fluidos Termicos',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Mantención y Producción.',
        'pdf': '../assets/temarios/Mantencion y Produccion/3.- Operacion de Calderas de Fluidos Termicos.docx',
        'image': '../assets/temario_mantencionYproduccion.jpg'
    },
    {
        'id': 7,
        'slug': 'metrologia-ajustes-y-tolerancias',
        'category': 'mantencion',
        'title': 'Metrologia, Ajustes y Tolerancias',
        'shortTitle': 'Metrologia, Ajustes y Tolerancias',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Mantención y Producción.',
        'pdf': '../assets/temarios/Mantencion y Produccion/4.- Metrologia, Ajustes y Tolerancias.docx',
        'image': '../assets/temario_mantencionYproduccion.jpg'
    },
    {
        'id': 8,
        'slug': 'soldadura-al-arco',
        'category': 'mantencion',
        'title': 'Soldadura al Arco',
        'shortTitle': 'Soldadura al Arco',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Mantención y Producción.',
        'pdf': '../assets/temarios/Mantencion y Produccion/5.- Soldadura al Arco.doc',
        'image': '../assets/temario_mantencionYproduccion.jpg'
    },
    {
        'id': 9,
        'slug': 'soldadura-tig-mig',
        'category': 'mantencion',
        'title': 'Soldadura TIG - MIG',
        'shortTitle': 'Soldadura TIG - MIG',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Mantención y Producción.',
        'pdf': '../assets/temarios/Mantencion y Produccion/6.- Soldadura TIG - MIG.doc',
        'image': '../assets/temario_mantencionYproduccion.jpg'
    },
    {
        'id': 10,
        'slug': 'mecanica-mantencion-maquinas-y-equipos-industriales',
        'category': 'mantencion',
        'title': 'Mecanica, Mantencion Maquinas y Equipos Industriales',
        'shortTitle': 'Mecanica, Mantencion Maquinas y Equipos Industriales',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Mantención y Producción.',
        'pdf': '../assets/temarios/Mantencion y Produccion/7.- Mecanica, Mantencion Maquinas y Equipos Industriales.docx',
        'image': '../assets/temario_mantencionYproduccion.jpg'
    },
    {
        'id': 11,
        'slug': 'instalacion-electrica-domiciliaria',
        'category': 'mantencion',
        'title': 'Instalacion electrica domiciliaria',
        'shortTitle': 'Instalacion electrica domiciliaria',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Mantención y Producción.',
        'pdf': '../assets/temarios/Mantencion y Produccion/8.- Instalacion electrica domiciliaria.docx',
        'image': '../assets/temario_mantencionYproduccion.jpg'
    },
    {
        'id': 12,
        'slug': 'administracion-de-bodegas',
        'category': 'mantencion',
        'title': 'Administracion de Bodegas',
        'shortTitle': 'Administracion de Bodegas',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Mantención y Producción.',
        'pdf': '../assets/temarios/Mantencion y Produccion/9.- Administracion de Bodegas.docx',
        'image': '../assets/temario_mantencionYproduccion.jpg'
    },
    {
        'id': 13,
        'slug': 'hidrauica-industrial',
        'category': 'mantencion',
        'title': 'Hidrauica Industrial',
        'shortTitle': 'Hidrauica Industrial',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Mantención y Producción.',
        'pdf': '../assets/temarios/Mantencion y Produccion/10.- Hidrauica Industrial.docx',
        'image': '../assets/temario_mantencionYproduccion.jpg'
    },
    {
        'id': 14,
        'slug': 'neumatica-basica',
        'category': 'mantencion',
        'title': 'Neumatica Basica',
        'shortTitle': 'Neumatica Basica',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Mantención y Producción.',
        'pdf': '../assets/temarios/Mantencion y Produccion/11.- Neumatica Basica.docx',
        'image': '../assets/temario_mantencionYproduccion.jpg'
    },
    {
        'id': 15,
        'slug': 'operacion-y-mantencion-de-gruas-horquillas',
        'category': 'maquinas',
        'title': 'Operacion y Mantencion de Gruas Horquillas',
        'shortTitle': 'Operacion y Mantencion de Gruas Horquillas',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Máquinas y Equipos.',
        'pdf': '../assets/temarios/Maquinas y Equipos/1.- Operacion y Mantencion de Gruas Horquillas.docx',
        'image': '../assets/temario_maquinasYequipos.jpg'
    },
    {
        'id': 16,
        'slug': 'operacion-y-mantencion-apiladores-electricos',
        'category': 'maquinas',
        'title': 'Operacion y Mantencion Apiladores Electricos',
        'shortTitle': 'Operacion y Mantencion Apiladores Electricos',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Máquinas y Equipos.',
        'pdf': '../assets/temarios/Maquinas y Equipos/2.- Operacion y Mantencion Apiladores Electricos.docx',
        'image': '../assets/temario_maquinasYequipos.jpg'
    },
    {
        'id': 17,
        'slug': 'operacion-de-alza-hombre-y-trabajos-en-altura',
        'category': 'maquinas',
        'title': 'Operacion de Alza Hombre y Trabajos en Altura',
        'shortTitle': 'Operacion de Alza Hombre y Trabajos en Altura',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Máquinas y Equipos.',
        'pdf': '../assets/temarios/Maquinas y Equipos/3.- Operacion de Alza Hombre y Trabajos en Altura.docx',
        'image': '../assets/temario_maquinasYequipos.jpg'
    },
    {
        'id': 18,
        'slug': 'operacion-y-mantencion-de-puente-gruas',
        'category': 'maquinas',
        'title': 'Operacion y mantencion de puente gruas',
        'shortTitle': 'Operacion y mantencion de puente gruas',
        'modality': 'presencial',
        'hours': '20',
        'desc': 'Curso técnico especializado en Máquinas y Equipos.',
        'pdf': '../assets/temarios/Maquinas y Equipos/4.- Operacion y mantencion de puente gruas (20 horas).docx',
        'image': '../assets/temario_maquinasYequipos.jpg'
    },
    {
        'id': 19,
        'slug': 'operacion-y-mantencion-de-transpaleta-electrica',
        'category': 'maquinas',
        'title': 'Operacion y Mantencion de Transpaleta Electrica',
        'shortTitle': 'Operacion y Mantencion de Transpaleta Electrica',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Máquinas y Equipos.',
        'pdf': '../assets/temarios/Maquinas y Equipos/5.- Operacion y Mantencion de Transpaleta Electrica.docx',
        'image': '../assets/temario_maquinasYequipos.jpg'
    },
    {
        'id': 20,
        'slug': 'operacion-y-mantencion-de-cargador-frontal',
        'category': 'maquinas',
        'title': 'Operacion y Mantencion de Cargador Frontal',
        'shortTitle': 'Operacion y Mantencion de Cargador Frontal',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Máquinas y Equipos.',
        'pdf': '../assets/temarios/Maquinas y Equipos/6.- Operacion y Mantencion de Cargador Frontal.docx',
        'image': '../assets/temario_maquinasYequipos.jpg'
    },
    {
        'id': 21,
        'slug': 'operacion-y-mantencion-de-minicargador-cargador-frontal',
        'category': 'maquinas',
        'title': 'Operacion y Mantencion de Minicargador - Cargador Frontal',
        'shortTitle': 'Operacion y Mantencion de Minicargador - Cargador Frontal',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Máquinas y Equipos.',
        'pdf': '../assets/temarios/Maquinas y Equipos/7.- Operacion y Mantencion de Minicargador - Cargador Frontal.docx',
        'image': '../assets/temario_maquinasYequipos.jpg'
    },
    {
        'id': 22,
        'slug': 'operacion-de-camion-ampliroll',
        'category': 'maquinas',
        'title': 'Operacion de camion Ampliroll',
        'shortTitle': 'Operacion de camion Ampliroll',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Máquinas y Equipos.',
        'pdf': '../assets/temarios/Maquinas y Equipos/8.- Operacion de camion Ampliroll.docx',
        'image': '../assets/temario_maquinasYequipos.jpg'
    },
    {
        'id': 23,
        'slug': 'operacion-y-mantencion-de-retroexcavadora',
        'category': 'maquinas',
        'title': 'Operacion y Mantencion de Retroexcavadora',
        'shortTitle': 'Operacion y Mantencion de Retroexcavadora',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Máquinas y Equipos.',
        'pdf': '../assets/temarios/Maquinas y Equipos/9.- Operacion y Mantencion de Retroexcavadora.docx',
        'image': '../assets/temario_maquinasYequipos.jpg'
    },
    {
        'id': 24,
        'slug': 'rigger',
        'category': 'maquinas',
        'title': 'Rigger',
        'shortTitle': 'Rigger',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Máquinas y Equipos.',
        'pdf': '../assets/temarios/Maquinas y Equipos/10.- Rigger.docx',
        'image': '../assets/temario_maquinasYequipos.jpg'
    },
    {
        'id': 25,
        'slug': 'seguridad-en-trabajo-de-altura',
        'category': 'seguridad',
        'title': 'Seguridad en Trabajo de Altura',
        'shortTitle': 'Seguridad en Trabajo de Altura',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Seguridad y Prevención de Riesgos.',
        'pdf': '../assets/temarios/Seguridad y Prevencion de riesgos/1.- Seguridad en Trabajo de Altura.docx',
        'image': '../assets/temario_seguridadYprevencion.jpg'
    },
    {
        'id': 26,
        'slug': 'tecnicas-de-primeros-auxilios',
        'category': 'seguridad',
        'title': 'Tecnicas de Primeros Auxilios',
        'shortTitle': 'Tecnicas de Primeros Auxilios',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Seguridad y Prevención de Riesgos.',
        'pdf': '../assets/temarios/Seguridad y Prevencion de riesgos/2.- Tecnicas de Primeros Auxilios.docx',
        'image': '../assets/temario_seguridadYprevencion.jpg'
    },
    {
        'id': 27,
        'slug': 'uso-y-manejo-de-extintores',
        'category': 'seguridad',
        'title': 'Uso y Manejo de Extintores',
        'shortTitle': 'Uso y Manejo de Extintores',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Seguridad y Prevención de Riesgos.',
        'pdf': '../assets/temarios/Seguridad y Prevencion de riesgos/3.- Uso y Manejo de Extintores.docx',
        'image': '../assets/temario_seguridadYprevencion.jpg'
    },
    {
        'id': 28,
        'slug': 'bpm',
        'category': 'seguridad',
        'title': 'BPM',
        'shortTitle': 'BPM',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Seguridad y Prevención de Riesgos.',
        'pdf': '../assets/temarios/Seguridad y Prevencion de riesgos/4.- BPM.docx',
        'image': '../assets/temario_seguridadYprevencion.jpg'
    },
    {
        'id': 29,
        'slug': 'food-defense',
        'category': 'seguridad',
        'title': 'Food Defense',
        'shortTitle': 'Food Defense',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Seguridad y Prevención de Riesgos.',
        'pdf': '../assets/temarios/Seguridad y Prevencion de riesgos/5.- Food Defense.docx',
        'image': '../assets/temario_seguridadYprevencion.jpg'
    },
    {
        'id': 30,
        'slug': 'trabajo-en-espacios-confinados',
        'category': 'seguridad',
        'title': 'Trabajo en espacios confinados',
        'shortTitle': 'Trabajo en espacios confinados',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Seguridad y Prevención de Riesgos.',
        'pdf': '../assets/temarios/Seguridad y Prevencion de riesgos/6.- Trabajo en espacios confinados.docx',
        'image': '../assets/temario_seguridadYprevencion.jpg'
    },
    {
        'id': 31,
        'slug': 'entrenamiento-de-brigadas-de-emergencia',
        'category': 'seguridad',
        'title': 'Entrenamiento de Brigadas de Emergencia',
        'shortTitle': 'Entrenamiento de Brigadas de Emergencia',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Seguridad y Prevención de Riesgos.',
        'pdf': '../assets/temarios/Seguridad y Prevencion de riesgos/7.- Entrenamiento de Brigadas de Emergencia.docx',
        'image': '../assets/temario_seguridadYprevencion.jpg'
    },
    {
        'id': 32,
        'slug': 'manejo-de-residuos-peligrosos',
        'category': 'seguridad',
        'title': 'Manejo de residuos peligrosos',
        'shortTitle': 'Manejo de residuos peligrosos',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Seguridad y Prevención de Riesgos.',
        'pdf': '../assets/temarios/Seguridad y Prevencion de riesgos/8.- Manejo de residuos peligrosos.docx',
        'image': '../assets/temario_seguridadYprevencion.jpg'
    },
    {
        'id': 33,
        'slug': 'prevencion-de-riesgos-electricos',
        'category': 'seguridad',
        'title': 'Prevencion de Riesgos Electricos',
        'shortTitle': 'Prevencion de Riesgos Electricos',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Seguridad y Prevención de Riesgos.',
        'pdf': '../assets/temarios/Seguridad y Prevencion de riesgos/9.- Prevencion de Riesgos Electricos.docx',
        'image': '../assets/temario_seguridadYprevencion.jpg'
    },
    {
        'id': 34,
        'slug': 'operacion-de-extintores-portatiles',
        'category': 'seguridad',
        'title': 'Operacion de Extintores Portatiles',
        'shortTitle': 'Operacion de Extintores Portatiles',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Seguridad y Prevención de Riesgos.',
        'pdf': '../assets/temarios/Seguridad y Prevencion de riesgos/10.- Operacion de Extintores Portatiles.docx',
        'image': '../assets/temario_seguridadYprevencion.jpg'
    },
    {
        'id': 35,
        'slug': 'prevencion-de-riesgos-laborales-autocuidado-y-seguridad',
        'category': 'seguridad',
        'title': 'Prevencion de riesgos laborales, autocuidado y seguridad',
        'shortTitle': 'Prevencion de riesgos laborales, autocuidado y seguridad',
        'modality': 'presencial',
        'hours': 'Consultar',
        'desc': 'Curso técnico especializado en Seguridad y Prevención de Riesgos.',
        'pdf': '../assets/temarios/Seguridad y Prevencion de riesgos/11.- Prevencion de riesgos laborales, autocuidado y seguridad.docx',
        'image': '../assets/temario_seguridadYprevencion.jpg'
    }
];
