const CURSOS_DATA = [
    {
        "id": 1,
        "slug": "exce-lavanzado",
        "category": "computacion",
        "modality": "presencial",
        "title": "Exce lAvanzado",
        "shortTitle": "Exce lAvanzado",
        "hours": "",
        "desc": "Exce lAvanzado - Curso técnico especializado.",
        "image": "../assets/temario_computacion.jpg",
        "pdf": "../assets/temarios/Computacion/Exce lAvanzado .docx"
    },
    {
        "id": 2,
        "slug": "excel-basico",
        "category": "computacion",
        "modality": "presencial",
        "title": "Excel Básico",
        "shortTitle": "Excel Básico",
        "hours": "",
        "desc": "Excel Básico - Curso técnico especializado.",
        "image": "../assets/temario_computacion.jpg",
        "pdf": "../assets/temarios/Computacion/Excel Ba╠üsico.docx"
    },
    {
        "id": 3,
        "slug": "excel-intermedio",
        "category": "computacion",
        "modality": "presencial",
        "title": "Excel Intermedio",
        "shortTitle": "Excel Intermedio",
        "hours": "",
        "desc": "Excel Intermedio - Curso técnico especializado.",
        "image": "../assets/temario_computacion.jpg",
        "pdf": "../assets/temarios/Computacion/Excel Intermedio.docx"
    },
    {
        "id": 4,
        "slug": "operacion-de-autoclaves-caldera-de-calefaccion-e-industrial",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Operación de Autoclaves, caldera de calefacción e industrial",
        "shortTitle": "Operación de Autoclaves, caldera de calefacción e industrial",
        "hours": "",
        "desc": "Operación de Autoclaves, caldera de calefacción e industrial - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/1.- Operacio╠ün de Autoclaves, caldera de calefaccio╠ün e industrial.docx"
    },
    {
        "id": 5,
        "slug": "operacion-de-autoclaves",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Operación de Autoclaves",
        "shortTitle": "Operación de Autoclaves",
        "hours": "",
        "desc": "Operación de Autoclaves - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/2.- Operacio╠ün de Autoclaves.docx"
    },
    {
        "id": 6,
        "slug": "operacion-de-calderas-de-fluidos-termicos",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Operación de Calderas de Fluidos Termicos",
        "shortTitle": "Operación de Calderas de Fluidos Termicos",
        "hours": "",
        "desc": "Operación de Calderas de Fluidos Termicos - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/3.- Operacio╠ün de Calderas de Fluidos Termicos.docx"
    },
    {
        "id": 7,
        "slug": "metrologia-ajustes-y-tolerancias",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Metrología, Ajustes y Tolerancias",
        "shortTitle": "Metrología, Ajustes y Tolerancias",
        "hours": "",
        "desc": "Metrología, Ajustes y Tolerancias - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/4.- Metrologi╠üa, Ajustes y Tolerancias.docx"
    },
    {
        "id": 8,
        "slug": "soldadura-al-arco",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Soldadura al Arco",
        "shortTitle": "Soldadura al Arco",
        "hours": "",
        "desc": "Soldadura al Arco - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/5.- Soldadura al Arco.doc"
    },
    {
        "id": 9,
        "slug": "soldadura-tig---mig",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Soldadura TIG - MIG",
        "shortTitle": "Soldadura TIG - MIG",
        "hours": "",
        "desc": "Soldadura TIG - MIG - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/6.- Soldadura TIG - MIG.doc"
    },
    {
        "id": 10,
        "slug": "mecanica-mantencion-maquinas-y-equipos-industriales",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Mecánica, Mantención Máquinas y Equipos Industriales",
        "shortTitle": "Mecánica, Mantención Máquinas y Equipos Industriales",
        "hours": "",
        "desc": "Mecánica, Mantención Máquinas y Equipos Industriales - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/7.- Meca╠ünica, Mantencio╠ün Ma╠üquinas y Equipos Industriales.docx"
    },
    {
        "id": 11,
        "slug": "instalacion-electrica-domiciliaria",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Instalación eléctrica domiciliaria",
        "shortTitle": "Instalación eléctrica domiciliaria",
        "hours": "",
        "desc": "Instalación eléctrica domiciliaria - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/8.- Instalacio╠ün ele╠üctrica domiciliaria.docx"
    },
    {
        "id": 12,
        "slug": "administracion-de-bodegas",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Administracion de Bodegas",
        "shortTitle": "Administracion de Bodegas",
        "hours": "",
        "desc": "Administracion de Bodegas - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/9.- Administracion de Bodegas.docx"
    },
    {
        "id": 13,
        "slug": "hidrauica-industrial",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Hidráuica Industrial",
        "shortTitle": "Hidráuica Industrial",
        "hours": "",
        "desc": "Hidráuica Industrial - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/10.- Hidra╠üuica Industrial.docx"
    },
    {
        "id": 14,
        "slug": "neumatica-basica",
        "category": "mantencion",
        "modality": "presencial",
        "title": "Neumática Básica",
        "shortTitle": "Neumática Básica",
        "hours": "",
        "desc": "Neumática Básica - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Mantencion y Produccion/11.- Neuma╠ütica Ba╠üsica.docx"
    },
    {
        "id": 15,
        "slug": "operacion-y-mantencion-de-gruas-horquillas",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operación y Mantención de Grúas Horquillas",
        "shortTitle": "Operación y Mantención de Grúas Horquillas",
        "hours": "",
        "desc": "Operación y Mantención de Grúas Horquillas - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/1.- Operacio╠ün y Mantencio╠ün de Gru╠üas Horquillas.docx"
    },
    {
        "id": 16,
        "slug": "operacion-y-mantencion-apiladores-electricos",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operación y Mantención Apiladores Eléctricos",
        "shortTitle": "Operación y Mantención Apiladores Eléctricos",
        "hours": "",
        "desc": "Operación y Mantención Apiladores Eléctricos - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/2.- Operacio╠ün y Mantencio╠ün Apiladores Ele╠üctricos.docx"
    },
    {
        "id": 17,
        "slug": "operacion-de-alza-hombre-y-trabajos-en-altura",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operación de Alza Hombre y Trabajos en Altura",
        "shortTitle": "Operación de Alza Hombre y Trabajos en Altura",
        "hours": "",
        "desc": "Operación de Alza Hombre y Trabajos en Altura - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/3.- Operacio╠ün de Alza Hombre y Trabajos en Altura.docx"
    },
    {
        "id": 18,
        "slug": "operacion-y-mantencion-de-puente-gruas-20-horas",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operación y mantención de puente grúas (20 horas)",
        "shortTitle": "Operación y mantención de puente grúas (20 horas)",
        "hours": "",
        "desc": "Operación y mantención de puente grúas (20 horas) - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/4.- Operacio╠ün y mantencio╠ün de puente gru╠üas (20 horas).docx"
    },
    {
        "id": 19,
        "slug": "operacion-y-mantencion-de-transpaleta-electrica",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operación y Mantención de Transpaleta Eléctrica",
        "shortTitle": "Operación y Mantención de Transpaleta Eléctrica",
        "hours": "",
        "desc": "Operación y Mantención de Transpaleta Eléctrica - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/5.- Operacio╠ün y Mantencio╠ün de Transpaleta Ele╠üctrica.docx"
    },
    {
        "id": 20,
        "slug": "operacion-y-mantencion-de-cargador-frontal",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operación y Mantención de Cargador Frontal",
        "shortTitle": "Operación y Mantención de Cargador Frontal",
        "hours": "",
        "desc": "Operación y Mantención de Cargador Frontal - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/6.- Operacio╠ün y Mantencio╠ün de Cargador Frontal.docx"
    },
    {
        "id": 21,
        "slug": "operacion-y-mantencion-de-minicargador---cargador-frontal",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operación y Mantención de Minicargador - Cargador Frontal",
        "shortTitle": "Operación y Mantención de Minicargador - Cargador Frontal",
        "hours": "",
        "desc": "Operación y Mantención de Minicargador - Cargador Frontal - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/7.- Operacio╠ün y Mantencio╠ün de Minicargador - Cargador Frontal.docx"
    },
    {
        "id": 22,
        "slug": "operacion-de-camion-ampliroll",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operación de camion Ampliroll",
        "shortTitle": "Operación de camion Ampliroll",
        "hours": "",
        "desc": "Operación de camion Ampliroll - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/8.- Operacio╠ün de camion Ampliroll.docx"
    },
    {
        "id": 23,
        "slug": "operacion-y-mantencion-de-retroexcavadora",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Operación y Mantención de Retroexcavadora",
        "shortTitle": "Operación y Mantención de Retroexcavadora",
        "hours": "",
        "desc": "Operación y Mantención de Retroexcavadora - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/9.- Operacio╠ün y Mantencio╠ün de Retroexcavadora.docx"
    },
    {
        "id": 24,
        "slug": "rigger",
        "category": "maquinas",
        "modality": "presencial",
        "title": "Rigger",
        "shortTitle": "Rigger",
        "hours": "",
        "desc": "Rigger - Curso técnico especializado.",
        "image": "../assets/temario_mantencionYproduccion.jpg",
        "pdf": "../assets/temarios/Maquinas y Equipos/10.- Rigger.docx"
    },
    {
        "id": 25,
        "slug": "seguridad-en-trabajo-de-altura",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Seguridad en Trabajo de Altura",
        "shortTitle": "Seguridad en Trabajo de Altura",
        "hours": "",
        "desc": "Seguridad en Trabajo de Altura - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/1.- Seguridad en Trabajo de Altura.docx"
    },
    {
        "id": 26,
        "slug": "tecnicas-de-primeros-auxilios",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Técnicas de Primeros Auxilios",
        "shortTitle": "Técnicas de Primeros Auxilios",
        "hours": "",
        "desc": "Técnicas de Primeros Auxilios - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/2.- Te╠ücnicas de Primeros Auxilios.docx"
    },
    {
        "id": 27,
        "slug": "uso-y-manejo-de-extintores",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Uso y Manejo de Extintores",
        "shortTitle": "Uso y Manejo de Extintores",
        "hours": "",
        "desc": "Uso y Manejo de Extintores - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/3.- Uso y Manejo de Extintores.docx"
    },
    {
        "id": 28,
        "slug": "bpm",
        "category": "seguridad",
        "modality": "presencial",
        "title": "BPM",
        "shortTitle": "BPM",
        "hours": "",
        "desc": "BPM - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/4.- BPM.docx"
    },
    {
        "id": 29,
        "slug": "food-defense",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Food Defense",
        "shortTitle": "Food Defense",
        "hours": "",
        "desc": "Food Defense - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/5.- Food Defense.docx"
    },
    {
        "id": 30,
        "slug": "trabajo-en-espacios-confinados",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Trabajo en espacios confinados",
        "shortTitle": "Trabajo en espacios confinados",
        "hours": "",
        "desc": "Trabajo en espacios confinados - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/6.- Trabajo en espacios confinados.docx"
    },
    {
        "id": 31,
        "slug": "entrenamiento-de-brigadas-de-emergencia",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Entrenamiento de Brigadas de Emergencia",
        "shortTitle": "Entrenamiento de Brigadas de Emergencia",
        "hours": "",
        "desc": "Entrenamiento de Brigadas de Emergencia - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/7.- Entrenamiento de Brigadas de Emergencia.docx"
    },
    {
        "id": 32,
        "slug": "manejo-de-residuos-peligrosos",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Manejo de residuos peligrosos",
        "shortTitle": "Manejo de residuos peligrosos",
        "hours": "",
        "desc": "Manejo de residuos peligrosos - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/8.- Manejo de residuos peligrosos.docx"
    },
    {
        "id": 33,
        "slug": "prevencion-de-riesgos-electricos",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Prevención de Riesgos Eléctricos",
        "shortTitle": "Prevención de Riesgos Eléctricos",
        "hours": "",
        "desc": "Prevención de Riesgos Eléctricos - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/9.- Prevencio╠ün de Riesgos Ele╠üctricos.docx"
    },
    {
        "id": 34,
        "slug": "operacion-de-extintores-portatiles",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Operación de Extintores Portatiles",
        "shortTitle": "Operación de Extintores Portatiles",
        "hours": "",
        "desc": "Operación de Extintores Portatiles - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/10.- Operacio╠ün de Extintores Portatiles.docx"
    },
    {
        "id": 35,
        "slug": "prevencion-de-riesgos-laborales-autocuidado-y-seguridad",
        "category": "seguridad",
        "modality": "presencial",
        "title": "Prevención de riesgos laborales, autocuidado y seguridad",
        "shortTitle": "Prevención de riesgos laborales, autocuidado y seguridad",
        "hours": "",
        "desc": "Prevención de riesgos laborales, autocuidado y seguridad - Curso técnico especializado.",
        "image": "../assets/temario_todoslostemarios.jpg",
        "pdf": "../assets/temarios/Seguridad y Prevencion de riesgos/11.- Prevencio╠ün de riesgos laborales, autocuidado y seguridad.docx"
    }
];